spring:
  jpa:
    show-sql: true

  datasource:
    url: jdbc:postgresql://localhost:5432/rbm_agendamento
    username: rbm_user
    password: rbm_password

  data:
    redis:
      host: localhost
      password: rbm_redis_pass

  rabbitmq:
    host: localhost
    username: rbm_user
    password: rbm_password

logging:
  level:
    com.rbm.agendamento: DEBUG
    org.springframework.security: DEBUG
    org.flywaydb: INFO
