server {
    listen 80;
    server_name rma.renatomota.online;

    client_max_body_size 16M;

    location /static/ {
        alias /var/www/wms-rma/app/static/;
        expires 30d;
        access_log off;
    }

    location / {
        proxy_pass http://unix:/run/wms-rma/wms-rma.sock;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
        proxy_redirect off;
    }
}
